apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: voltdb-pvc
  namespace: volt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-uploads-pvc
  namespace: volt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---

