name: Client CI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup dependency cache
        uses: actions/cache@v4
        with:
          path: |
            client/node_modules
            ~/.bun/install/cache
          key: bun-${{ hashFiles('client/bun.lockb') }}
          restore-keys: |
            bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type checks
        run: bun run type:check

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run Biome
        run: biome ci
